temperature_2m: FloatType
relative_humidity_2m: IntegerType
apparent_temperature: FloatType
precipitation: FloatType
wind_speed_10m: FloatType
wind_speed_100m: FloatType
creation_time: TimestampType
sensor_id: StringType
count: IntegerType
is_holiday: IntegerType
consumed_unit: FloatType
lag1: FloatType
lag2: FloatType
lag3: FloatType
lag4: FloatType
lag5: FloatType
lag6: FloatType
lag7: FloatType
day: IntegerType
hour: IntegerType
month: IntegerType
dayofweek: IntegerType
quarter: IntegerType
dayofyear: IntegerType
weekofyear: IntegerType
year: IntegerType
